export const mockPosts = [
  {
    id: "1",
    title: "Spam link here",
    content: "Check out this shady site...",
    author: { id: "u1", username: "spammer123" },
    reportedReason: "Spam",
    reportedAt: "2025-09-01T10:30:00Z",
    status: "pending",
    reportCount: 3,
    images: ["https://picsum.photos/seed/spam1/800/600"],
  },
  {
    id: "2",
    title: "Offensive comment",
    content: "You are so dumb!",
    author: { id: "u2", username: "toxicUser" },
    reportedReason: "Harassment",
    reportedAt: "2025-09-01T11:00:00Z",
    status: "pending",
    reportCount: 2,
    images: ["https://picsum.photos/seed/toxic2/800/600"],
  },
  {
    id: "3",
    title: "Fake news article",
    content: "Breaking: Aliens landed in my backyard!",
    author: { id: "u3", username: "fakeNewsGuy" },
    reportedReason: "Misinformation",
    reportedAt: "2025-09-01T11:30:00Z",
    status: "pending",
    reportCount: 5,
    images: ["https://picsum.photos/seed/fake3/800/600"],
  },
  {
    id: "4",
    title: "Off-topic post",
    content: "Anyone wants to trade Pokémon cards here?",
    author: { id: "u4", username: "randomUser" },
    reportedReason: "Off-topic",
    reportedAt: "2025-09-01T12:00:00Z",
    status: "pending",
    reportCount: 1,
    images: ["https://picsum.photos/seed/pokemon4/800/600"],
  },
  {
    id: "5",
    title: "Hate speech",
    content: "People like you don’t belong here!",
    author: { id: "u5", username: "angryUser" },
    reportedReason: "Hate Speech",
    reportedAt: "2025-09-01T12:30:00Z",
    status: "pending",
    reportCount: 4,
    images: ["https://picsum.photos/seed/hate5/800/600"],
  },
  {
    id: "6",
    title: "Inappropriate image",
    content: "NSFW content posted",
    author: { id: "u6", username: "nsfwUploader" },
    reportedReason: "Inappropriate Content",
    reportedAt: "2025-09-01T13:00:00Z",
    status: "pending",
    reportCount: 6,
    images: ["https://picsum.photos/seed/nsfw6/800/600"],
  },
  {
    id: "7",
    title: "Political rant",
    content: "This party should be banned!",
    author: { id: "u7", username: "politico" },
    reportedReason: "Hate Speech",
    reportedAt: "2025-09-01T13:30:00Z",
    status: "pending",
    reportCount: 3,
    images: ["https://picsum.photos/seed/politic7/800/600"],
  },
  {
    id: "8",
    title: "NSFW language",
    content: "This is ****!",
    author: { id: "u8", username: "swearMaster" },
    reportedReason: "Offensive Language",
    reportedAt: "2025-09-01T14:00:00Z",
    status: "pending",
    reportCount: 2,
    images: ["https://picsum.photos/seed/language8/800/600"],
  },
  {
    id: "9",
    title: "Phishing attempt",
    content: "Enter your bank details here...",
    author: { id: "u9", username: "phisher" },
    reportedReason: "Scam",
    reportedAt: "2025-09-01T14:30:00Z",
    status: "pending",
    reportCount: 8,
    images: ["https://picsum.photos/seed/phish9/800/600"],
  },
  {
    id: "10",
    title: "Copyright violation",
    content: "Here’s a leaked movie!",
    author: { id: "u10", username: "pirate" },
    reportedReason: "Copyright Violation",
    reportedAt: "2025-09-01T15:00:00Z",
    status: "pending",
    reportCount: 5,
    images: ["https://picsum.photos/seed/movie10/800/600"],
  },
  {
    id: "11",
    title: "Trolling",
    content: "Your opinion is trash 😂",
    author: { id: "u11", username: "troll" },
    reportedReason: "Harassment",
    reportedAt: "2025-09-01T15:30:00Z",
    status: "pending",
    reportCount: 4,
    images: ["https://picsum.photos/seed/troll11/800/600"],
  },
  {
    id: "12",
    title: "Clickbait",
    content: "You won’t believe what happened next!",
    author: { id: "u12", username: "clickMaster" },
    reportedReason: "Spam",
    reportedAt: "2025-09-01T16:00:00Z",
    status: "pending",
    reportCount: 3,
    images: ["https://picsum.photos/seed/clickbait12/800/600"],
  },
  {
    id: "13",
    title: "Religious hate",
    content: "People of XYZ religion are bad!",
    author: { id: "u13", username: "hateUser" },
    reportedReason: "Hate Speech",
    reportedAt: "2025-09-01T16:30:00Z",
    status: "pending",
    reportCount: 7,
    images: ["https://picsum.photos/seed/religion13/800/600"],
  },
  {
    id: "14",
    title: "Dangerous challenge",
    content: "Try this risky stunt at home!",
    author: { id: "u14", username: "stuntGuy" },
    reportedReason: "Unsafe Content",
    reportedAt: "2025-09-01T17:00:00Z",
    status: "pending",
    reportCount: 6,
    images: ["https://picsum.photos/seed/danger14/800/600", "https://picsum.photos/seed/danger14b/800/600"],
  },
  {
    id: "15",
    title: "Personal info leaked",
    content: "Here’s John’s phone number...",
    author: { id: "u15", username: "leaker" },
    reportedReason: "Privacy Violation",
    reportedAt: "2025-09-01T17:30:00Z",
    status: "pending",
    reportCount: 9,
    images: ["https://picsum.photos/seed/privacy15/800/600"],
  },
];
